swagger: "2.0"
info:
  description: "RESULT EMPLOYMENT TASK"
  version: "1.0.0"
  title: "RESULT-TESTK"
  contact:
    email: "aljazpoglavc1@gmail.com"
basePath: "/v1"
paths:
  /Call:
    get:
      summary: Get data from URL
      description: |
        Get data from URL's
	* https://www.result.si/projekti/
	* https://www.result.si/o-nas/	
	* https://www.result.si/kariera/
	* https://www.result.si/blog/
        * if apiCall is provided (min value 1, max 4) > return all data from URL's. Also return succesfull and not succesfull calls.
        * if apiCall > 4 or < 1 return empty array
      operationId: getDataFromUrl
      parameters:
        - name: apiCall
          in: query
          description: Number of Asynchronous calls
          required: false
          type: number
      produces:
        - "application/json"
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              stations:
                type: array
                items:
                  type: object
                  required:
                    - text
                    - url
                    - succesfullcalls
                    - distance
                    - notSuccesfullcalls
                  properties:
                    text:
                      type: string
                      description: |
                        Scrape main text from input URL
                        Mapping: `//*[@id="finance_kontroling"]/section/div[1]/div/div/h2`
                      example: Izzivi in rešitve

                    url:
                      type: string
                      description: |
                        Get URL path from where text is taken.
                        Mapping: `//*[@id="finance_kontroling"]/section/div[1]/div/div/h2`
                      example: https://www.result.si/projekti/

                    succesfullcalls:
                      type: number
                      description: |
                        If call was succesfull it gets value 1
                        Mapping: `//*[@id="finance_kontroling"]/section/div[1]/div/div/h2`
                      example: 1

                    notSuccesfullcalls:
                      type: number
                      description: |
                        If call wasn't succesfull it gets value 1
                        Mapping: `//*[@id="finance_kontroling"]/section/div[1]/div/div/h2`
                      example: 1

        "400":
          description: Bad request
        "500":
          description: Server error
